### ISSUE TITLE
Add array support in Dockerfile

### ISSUE THREAD

**Issue by yurinnick** [docker-tow/tow#3]
Tow doesn't understand constructions like:

```
VOLUME [
 ...
]
```

**Comment by alekseiko** [comment]
Tow does not parse any volume constructions. Could you post stack trace?

**Comment by yurinnick** [comment]
FATA[0000] Error: We do not understand this file. Please ensure it is a valid Dockerfile. Parser error at "\"/var/www/html\","

```
VOLUME [
  "/var/www/html",
  "/etc/nginx"
]
```

**Comment by alekseiko** [comment]
This error from docker itself.
