### ISSUE TITLE
Files and templates paths should contain directory name in mapping.py

### ISSUE THREAD

**Issue by yurinnick** [docker-tow/tow#5]
- Require folder definition in mapping.py
- Add support of subdirectories in `files` and `templates` folders

Example:

```
mapping = [
    ("files/test.conf", "/tmp/example/file.conf"),
    ("templates/test.conf", "/tmp/example/template.conf"),
    ("templates/demo/test.conf", "/tmp/demo/template.conf"),
]
```

**Comment by alekseiko** [comment]
Subdirectories in templates and files are supported that's why I didn't want to add folder definition

**Comment by yurinnick** [comment]
Subdirectories for files and templates aren't working, plz fix it.

**Comment by alekseiko** [comment]
What do think if we have the following format:

```
mapping = {"templates":[("conf/test.tmpl", "/etc/config"),("config2.tmpl", "/var/lib/config2", "600")],
 "files":[("id_rsa",".ssh/id_rsa")]}
```
